# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Main

on:
  push:
    branches: [ "main" ]

jobs:

  check:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: make check

  test:
    needs: check
    runs-on: self-hosted
    steps:
    - name: Test
      run: make test

  codecov:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
